name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}Bukkit
version: ${project.version}
api-version: 1.13
author: MiaoWoo
website: ${ciManagement.url}
softdepend:
  - PlaceholderAPI
  - AttributePlus
  - PlayerPoints
  - CrazyCrates
  - ProtocolLib
  - DragonCore
  - MythicMobs
  - WorldGuard
  - Adyeshach
  - WorldEdit
  - SkillAPI
  - TradeMe
  - Chemdah
  - Vault
